
main: part1 part2

CXX_FLAGS=-std=c++17

DAY=day7
part1: 
	g++ $(CXX_FLAGS) $(DAY)_1.cpp -o out_$(DAY)_1
	./out_$(DAY)_1

part2: 
	g++ $(CXX_FLAGS) $(DAY)_2.cpp -o out_$(DAY)_2
	./out_$(DAY)_2

clean: 
	rm out_$(DAY)_*
